version: 3

tasks:
  default:
    - ruff check . --fix --fixable=ALL
    - black .
    - mypy .

  dev:
    dotenv: [ .env ]
    env:
      PYTHONPATH: './'
    sources:
      - .env
      - '**/*.py'
      - exclude: .venv/**/*
      - '**/*.yaml'
    generates:
      - a-path-wont-exists
    cmds:
      - python app/main.py

  wiki:
    dotenv: [ .env ]
    cmds:
      - python -m app.wiki_date

  run:
    dotenv: [ .env ]
    cmds:
      - python {{.CLI_ARGS}}
