name: test

on:
  push:
    branches-ignore:
      - renovate/**
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - master
    paths-ignore:
      - "**.md"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - uses: trim21/setup-poetry@dist/v2
      - uses: trim21/install-poetry-project@dist/v2

      - run: pytest -v
